AllCops:
  NewCops: enable
  SuggestExtensions: false

# Relax metrics for CLI tool - focus on functionality over strict metrics
Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ParameterLists:
  Max: 8

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

# Allow longer blocks in specs - they're descriptive test suites
Metrics/BlockLength:
  Enabled: false

# Disable documentation requirement - this is a CLI tool with clear naming
Style/Documentation:
  Enabled: false

# Allow predicate method naming patterns common in Ruby - validate_name is fine
Naming/PredicatePrefix:
  Enabled: false

# Allow methods that don't end with ? - validate_name, remove_worktree etc make sense
Naming/PredicateMethod:
  Enabled: false

# Allow boolean parameters for CLI options - they're clear in context
Style/OptionalBooleanParameter:
  Enabled: false

# Format strings are fine for CLI output - annotated tokens add noise
Style/FormatStringToken:
  Enabled: false

# Allow unused method arguments with underscore prefix
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# Be more lenient with line length for CLI tools
Layout/LineLength:
  Max: 150

# Allow development dependencies in gemspec for published gems
Gemspec/DevelopmentDependencies:
  Enabled: false