openapi: 3.1.0
info:
  title: Worktrees Management API (contract for CLI behaviors)
  version: 0.1.0
paths:
  /worktrees:
    get:
      summary: List worktrees
      parameters:
        - in: query
          name: filterName
          schema: { type: string }
        - in: query
          name: filterBase
          schema: { type: string }
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
        - in: query
          name: pageSize
          schema: { type: integer, minimum: 1, maximum: 100, default: 20 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Worktree'
                  page: { type: integer }
                  pageSize: { type: integer }
                  total: { type: integer }
    post:
      summary: Create a worktree
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ name ]
              properties:
                name: { type: string }
                base: { type: string }
                root: { type: string }
                reuseBranch: { type: boolean }
                siblingSuffix: { type: string }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worktree'
  /worktrees/{name}/switch:
    post:
      summary: Switch to a worktree by name
      parameters:
        - in: path
          name: name
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  current: { $ref: '#/components/schemas/WorktreeRef' }
                  previous: { $ref: '#/components/schemas/WorktreeRef' }
                  warnings:
                    type: array
                    items: { type: string }
  /worktrees/{name}:
    delete:
      summary: Remove a worktree
      parameters:
        - in: path
          name: name
          required: true
          schema: { type: string }
        - in: query
          name: deleteBranch
          schema: { type: boolean }
        - in: query
          name: mergedInto
          schema: { type: string }
        - in: query
          name: force
          schema: { type: boolean }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  removed: { type: boolean }
                  branchDeleted: { type: boolean }
  /status:
    get:
      summary: Show current worktree status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorktreeRef'
components:
  schemas:
    Worktree:
      type: object
      properties:
        name: { type: string }
        branch: { type: string }
        baseRef: { type: string }
        path: { type: string }
        active: { type: boolean }
        isDirty: { type: boolean }
        hasUnpushedCommits: { type: boolean }
    WorktreeRef:
      type: object
      properties:
        name: { type: string }
        path: { type: string }


